# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - DPS-Angular-Project

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@7.2
    npm install
    ng build --output-path $(Build.ArtifactStagingDirectory)/dist_test
    ng build --configuration=staging --output-path $(Build.ArtifactStagingDirectory)/dist_stag
    ng build --configuration=temp-prod --output-path $(Build.ArtifactStagingDirectory)/dist_prod
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
