export const environment = {
  production: true,
  dataFromAPI_JSON: false, // True = From Remote :: False = From JSON
  dpsAPI: 'https://dpsapisdev.azurewebsites.net/api/',
  boemmAPI : 'https://boemmapidev.azurewebsites.net/api/',
  getCustomers: 'Customer',
  getCustomerLists: 'Customer/GetAllCustomersPreviewJson',
  getCustomerByVatNumber: 'Customer/GetCustomerByVatNumber',
  getCustomerByVatNumberEdit:'Customer/',
  createCustomer: 'Customer',
  getUsers: 'User',
  getUserByUsername: 'User/User',
  createUser: 'User/Create',
  getLegalForm: '',
  getCounteries: '',
  getParitairCommitee: 'ParitairCommitee',
  getStatute: '',
  getCodes: 'code',
  getLanguages: '',
  getWorkSchedule: 'User/{CustomerVatNumber}',
  getPosition: 'User/{CustomerVatNumber}',
  getLocations: 'Location',
  createLocation: 'Location',
};
